trusted_config_paths = ["~/projects/**"]

[tools]
ast-grep = "latest"
bat = "latest"
bun = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
lazygit = "latest"
op = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
zig = "latest"
