[settings]
trusted_config_paths = ["/Users/dhamidi/projects"]

[tools]
ast-grep = "latest"
bat = "latest"
bun = "latest"
cmake = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
"github:dhamidi/kit" = "v0.2.1"
lazygit = "latest"
node = "latest"
op = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
zig = "latest"
